<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Agripa</AssemblyName>
    <Product>Agripa</Product>
    <Title>Agripa</Title>
    <ApplicationIcon>Assets/agripa.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/agripa.ico" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>
</Project>
